use_frameworks!

target 'UIKit-AKExtension_Example' do
  pod 'UIKit-AKExtension/Extensions', :path => '../'
  pod 'UIKit-AKExtension/Inherits', :path => '../'

  target 'UIKit-AKExtension_Tests' do
    inherit! :search_paths

    
  end
end
